### ISSUE TITLE
Error with more than 4 double quotes on a line

### ISSUE THREAD

**Issue by mrtazz** [Townk/vim-autoclose#1]
If more than 4 double quotes are present in one line, the following error occurs:

```
Error detected while processing function <SNR>21_CheckPair..<SNR>21_CountQuotes..<SNR>
21_RemoveQuotes:
line   25:
E684: list index out of range: 6 
```

**Comment by anttih** [comment]
I'm having the same issue. Any tips/ideas on how to fix this?

**Comment by ku1ik** [comment]
The same problem for me. Townk, do you have idea which commit could break it?

**Comment by mattly** [comment]
likewise. this is getting really annoying.

**Comment by haguro** [comment]
ditto.

**Comment by raskchanky** [comment]
I had this same problem and fixed it by removing this plugin and installing this one instead http://www.vim.org/scripts/script.php?script_id=1849

**Comment by mrtazz** [comment]
Works for me, too. there is also a [github mirror](http://github.com/vim-scripts/AutoClose) of the script if you use submodules and pathogen.

**Comment by lynndylanhurley** [comment]
I'm having the same issue:

```
Error detected while processing function <SNR>21_CheckPair..  
<SNR>21_CountQuotes..<SNR>
21_RemoveQuotes:
line   25:
E684: list index out of range: 6 
```

I like this AutoClose plugin better than the other AutoClose or delimitMate, but this issue makes it un-usable for me. Any fixes yet?

**Comment by ku1ik** [comment]
It was the best one, indeed. But looks like Townk disappeared :(

**Comment by mtvee** [comment]
gah, ...this was driving me bananers... forked it and this one works for me...
https://github.com/mtvee/vim-autoclose

fixes the single quote issue too

**Comment by mrtazz** [comment]
works great for me, too.

Thanks mtvee.

**Comment by Townk** [comment]
Sorry for the long hiatus, yesterday I post a fix for this issue.
Thanks

**Comment by mtvee** [comment]
Thanks Townk! Welcome back :)
