### ISSUE TITLE
when enter auto open block {} and indent

### ISSUE THREAD

**Issue by guileen** [Townk/vim-autoclose#17]
`I` means the cursor.

`I{` go to `{I}`, and at this cursor, I press `enter`, it become

```
 {
 I}
```

I wish it could be

```
{
    I
}
```

Is this possible?

**Comment by artm** [comment]
I have this in my branch, it's a bit experimental at the moment but I think it does what you ask

**Comment by ivotron** [comment]
[This](http://www.vim.org/scripts/script.php?script_id=1849) plugin does it

**Comment by casey-chow** [comment]
@ivotron It doesn't seem to do that for me.

**Comment by ivotron** [comment]
you have to type { twice so that it inserts } and places the cursor at the correct indented level. For example:

``` c
void main() { (then { again)
```

and it transforms into:

``` c
void main()
{
    _
}
```

Im using "_" to denote the cursor
