### ISSUE TITLE
using single quotes ends up inserting extra quote

### ISSUE THREAD

**Issue by tmm1** [Townk/vim-autoclose#2]
if i type "hello" I end up with "hello"

but if i type 'hello' I end up with 'hello''

**Comment by wuputah** [comment]
+1, I found this too. :)

**Comment by wuputah** [comment]
This patch seems to fix the problem, but I'm not sure why the code was there to begin with. Perhaps it was targeting a language where quote behavior is different.

https://github.com/wuputah/vim-autoclose/commit/c01db7691591208a2096cafa495c84f2c72c315c

**Comment by wuputah** [comment]
After some coding, I figured out that the code is trying to handle the case where a single quote is used as an apostrophe. The language where quote behavior is different is English!

**Comment by Townk** [comment]
Hey guys, I cannot access the repository on the comment anymore, but I'll look into this issue tonight!

Thanks

**Comment by Townk** [comment]
Just pushed a fix for this. Please test!

**Comment by wuputah** [comment]
Updated my comment with correct link, but I'm sure your patch is better. :)
