### ISSUE TITLE
autoclose breaks nocompatibility

### ISSUE THREAD

**Issue by orlando** [Townk/vim-autoclose#30]
using autoclose in ubuntu 11.10 breaks nocompatibility, so it writes ABCD when you press arrows keys in insert mode..

**Comment by artm** [comment]
is this in terminal vim or in gvim?

On Wed, May 2, 2012 at 2:04 AM, Orlando Del Aguila <
reply@reply.github.com

> wrote:
> 
> using autoclose in ubuntu 11.10 breaks nocompatibility, so it writes ABCD
> when you press arrows keys in insert mode..
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Townk/vim-autoclose/issues/30

## 

Artm Baguinski,
Software Engineer,
V2_ Institute for the Unstable Media, http://www.v2.nl/

tel: +31.6.29394010
skype: v2_artm
web: http://claimid.com/artm/

**Comment by orlando** [comment]
in terminal... in gvim works perfectly... i switched to [auto-pairs](https://github.com/vim-scripts/Auto-Pairs) for now, i tried all fixes that i could find and nothing worked...

i tried all fixes in this page [fixes](http://vim.wikia.com/wiki/Fix_arrow_keys_that_display_A_B_C_D_on_remote_shell)

**Comment by artm** [comment]
hi again

here is what's happening: we install a map for the Escape key (part of dot-register preservation code), but in terminal special keys are implemented as escape sequences. There is a different set of mappings that attempts to restore the escape sequences in known terminals, which should have solved your problem. But either vim doesn't report the terminal type correctly or the terminal uses different escape sequences (very unlikely).

to investigate this further, what does `:echo &term` reports inside vim in terminal?

**Comment by orlando** [comment]
im using this line in .vimrc

```
set term=gnome-256color
```

together with CSApprox.vim to be able to use non 256bits colorschemes in terminal..

changing this line to

```
set term=xterm-256color
```

works perfect (for both AutoClose.vim and CSApprox.vim)

thanks for your time @artm :smiley:

btw.. i was getting this issue also when searching with Command-T, but setting &term to 'xterm' instead of 'gnome' fixed that problem too..

**Comment by artm** [comment]
ah, but that means we have to add 'gnome' to the list of terminals that need to be fixed.
