### ISSUE TITLE
Autoclosing of quotes doesn't seem to work on Gvim

### ISSUE THREAD

**Issue by pabloh** [Townk/vim-autoclose#32]
Autoclosing of quotes (like ' or ") doesn't work on gvim but works fine on text mode vim.

**Comment by artm** [comment]
what OS are you on? could it be that gvim loads some other plugin that conflicts with autoclose?

**Comment by pabloh** [comment]
I'm using Ubuntu 12.04, oddly it seems the vividchalck colorscheme I'm using is conflicting with autoclose, if I use another one the problem disappears.
Here's a copy of the colorscheme flle: https://gist.github.com/2731180

**Comment by Townk** [comment]
I just tried vividchalck from the gist you send us and everything is working as expected.
Try the latest version of plugin.

**Comment by dvcrn** [comment]
I have a similar issue with the gruvbox theme https://github.com/morhetz/gruvbox. Whenever I activate the theme, I don't get completion on quotes. Only happens with this theme though
