### ISSUE TITLE
Delay in change mode

### ISSUE THREAD

**Issue by gilsondev** [Townk/vim-autoclose#34]
When you exit the insert mode to normal mode, it has a delay.

**Comment by Townk** [comment]
Sorry, I can't reproduce this. I tried on terminal and GUI and on both I can exit insert mode without delay.

My computer is a 2009 Macbook Pro laptop with a Core 2 Duo 2.53. For the current computer standards I have a "slow" machine.

Did you tried this with a vanilla Vim with only Autoclose installed?

**Comment by Townk** [comment]
I think I found the problem but unfortunately there is no easy solution.

The delay happens only on terminal when you have the g:AutoClosePreserveDotReg set to 1.

When user wants to preserve the Dot registry (so you can press '.' and have your autoclose also inserted as last action) we have to map some special keys to save user's movement into a local buffer. One of those keys is the <Esc> key. If you check your imaps for <Esc> (:imap <Esc>) you'll see that we have lots of <Esc> mapping.

So when you press <Esc> vim waits some time before delivering the <Esc> press to the correct map.

The workaround for this is to not preserve the dot registry adding the following line on your .vimrc:

let g:AutoClosePreserveDotReg = 0

This will avoid the delays on the <Esc> keys. Now you have to check which of the two features is more important to you: the dot registry or the fast <Esc>.

**Comment by gilsondev** [comment]
Thank you ;)
