### ISSUE TITLE
Problems with special keys (vt100-cursor-keys), sent as "^[OA" etc.

### ISSUE THREAD

**Issue by blueyed** [Townk/vim-autoclose#4]
While using the plugin I've noticed that it messes up special keys like the cursor keys, or <end>.

When using Ctrl-V in insert mode I see that e.g. "<up>" gets sent as `^[OA`.  
This is covered in Vim's help at `:h vt100-cursor-keys`.

What happens here is that the `[` in this sequence appears to get used by autoclose and/or confuses Vim.  
I can work around this by manually mapping the cursor keys, like `map! ^[OA <up>` (lhs via `C-v<up>`) in vimrc, but there might be a better fix for this.

btw: do you know about another AutoClose script, which is located at https://github.com/vim-scripts/AutoClose ? (it faces the same problem though)

**Comment by blueyed** [comment]
The "other autoclose" has code to address this, which I just had to expand to also fix "term=screen".

See https://github.com/blueyed/AutoClose/commit/a3c49439d02c976ed945605397b1b5871c830284 - please consider applying the same mechanism to fix this to "this autoclose".

**Comment by blueyed** [comment]
Fixed in https://github.com/blueyed/vim-autoclose/commit/91337868f6738b31f9c2bbe0a221a42152b64cce - should be in the pull request, too.

**Comment by Townk** [comment]
I did a pull of Artem's repositories with the fixes from blueyed. Can you check if I can close this issue?

**Comment by artm** [comment]
ah, in my master ([next commit after the merge point](https://github.com/artm/vim-autoclose/commit/109cc7931f2c7463af32dce33efd80d8aa985ff6) ) there is an alternative implementation of this solution. It's probably a bit controversial though and I still want to read more how other projects go about this. 

But so far in many combinations of osx, windows and linux terminals, and ssh and tmux sessions I haven't had this problem come back with either the solution in your tree or in mine. I've spent some time testing it (disabling and reenabling the workaround). But it could be just luck.
