### ISSUE TITLE
Autoclosing of quotes(' ")  doesn't work on macvim

### ISSUE THREAD

**Issue by yam-liu** [Townk/vim-autoclose#45]
It cannot close automatically like this  http://minus.com/mLEcsm6niuXDl

os x 10.8.0    macvim snapshot65

colorscheme molokai  (I think it's irrelevant)

**Comment by 907th** [comment]
Confirm... Strange behaviour in erb/haml files

**Comment by ivang** [comment]
It seems that this problem only arises when using certain colorschemes (e.g. "slate") that redefine the 'String' and/or 'Character' syntax regions. You can try using a different colorscheme or you can make [a small change](https://github.com/ivang/vim-autoclose/commit/bb9ffff989b0db6756398ebcd5774e2df11596fc) in your AutoClose.vim.

This might also fix issue #43.

**Comment by yam-liu** [comment]
Thanks for your reply. I will try.
