### ISSUE TITLE
It makes 'Esc' command hang

### ISSUE THREAD

**Issue by Netherdrake** [Townk/vim-autoclose#57]
I've been having this issue, where Escaping from insert mode from normal mode takes over a second, as if Esc was already binded to something.
When Esc is pressed twice, the switch to normal mode is instant.

So I went over my vimrc and disabled each plugin individually to figure out which one is causing the problem. Well turns out its 3 of em, and yours is one.

Heres my vimrc.
https://bitbucket.org/furion/dotfiles/src/dc572002721f2bf26136e40f951d45373de3c174/.vimrc?at=master

Do you have any idea how to fix this?

**Comment by xiaogwu** [comment]
I have witnessed the same issue myself but the odd thing is it only happens in regular command line vim but isn't an issue if you use MacVim.

**Comment by pyro2927** [comment]
3rding the issue.

**Comment by xiaogwu** [comment]
For those who are looking for an alternative might consider Raimondi/delimitMate which provides similar functionality as this plugin but doesn't cause the "Esc" issue being reported in this issue.

**Comment by Netherdrake** [comment]
There are many plugins that cause this. But I've got a working solution, recommended by some fellow GitHuber. Its been working for me perfectly for months now:

`" vim mode-switch lag fix
if ! has("gui_running")
    set ttimeoutlen=10
    augroup FastEscape
        autocmd!
        au InsertEnter * set timeoutlen=0
        au InsertLeave * set timeoutlen=1000
    augroup END
endif`

**Comment by seagoj** [comment]
This really should be added to the README somewhere. I  was close to uninstalling the plugin before I came upon this issue.

**Comment by ghost** [comment]
Same issue here, without any timeout. The snipplet above won't change anything.
Conf: https://github.com/Ilias95/dotfiles/tree/master/vim

**Comment by ghost** [comment]
Try Esc and die like the rest, what a "mode jumper".

```
Try 1
  Esc :wq -> normal mode ->insert mode -> normal mode -> nothing saved

Try 2
  Esc :wq -> normal mode ->insert mode -> normal mode -> still nothing saved

Try 3

  Esc :wq -> normal mode ->insert mode -> normal mode -> still nothing saved

Try 4

SHIFT + DELETE this crap

```

You know what they say, don't change something when it works, so I will go back and stick to lexima.
