### ISSUE TITLE
Incompatibility with Quicktex

### ISSUE THREAD

**Issue by ryan-ph** [Townk/vim-autoclose#76]
Both autoclose and Quicktex both remap the space key, so there's a conflict with the two plugins. What does autoclose use the space key for, and is there a way to remap it?

**Comment by ghost** [comment]
@ryanp97 I am not sure if you're still using this plugin, but this should be fixed in AutoClose 2.1, which is my fork of the project. You can find it here: https://github.com/whitehatzero/vim-autoclose
