### ISSUE TITLE
navigation keys in insert mode don't work

### ISSUE THREAD

**Issue by rodolf0** [Townk/vim-autoclose#9]
When working in insert mode using navigation keys <up> <down> <left> <right> or <del> doesn't work as expected, instead it inserts upper case alpha chars.

**Comment by Townk** [comment]
Sorry for the long wait to repply.

If you check the documentation and the previous defects opened on GitHub
you'll find out the reason why this happens and possible workarounds.

Thanks,

On Thu, May 26, 2011 at 3:15 PM, warlockcc <
reply@reply.github.com>wrote:

> When working in insert mode using navigation keys <up> <down> <left>
> <right> or <del> doesn't work as expected, instead it inserts upper case
> alpha chars.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Townk/vim-autoclose/issues/9

## 

Thiago Alves
Computer Scientist

http://www.thiagoalves.com.br

## talk@thiagoalves.com.br

"Man's mind, once stretched by a new idea, never regain its original
dimensions."
-Oliver Wendell Holmes

**Comment by rodolf0** [comment]
I found it, thought I had closed/deleted the issue. Sorry for my mistake here.
- Rodolfo

On Tue, Jun 7, 2011 at 4:33 PM, Townk
reply@reply.github.com
wrote:

> Sorry for the long wait to repply.
> 
> If you check the documentation and the previous defects opened on GitHub
> you'll find out the reason why this happens and possible workarounds.
> 
> Thanks,
> 
> On Thu, May 26, 2011 at 3:15 PM, warlockcc <
